#
# syntax: https://docs.docker.com/compose/yml/
#

version: "2"

services:
    bilyric-server:
        restart: always
        image: cuongnb14/bilyric:0.1
        networks:
            - onfta-back
        expose:
            - "8000"
        ports:
            - "8000:8000"
        volumes:
            - .:/usr/src/app
        env_file: docker-env
        environment:
            DJANGO_SETTINGS_MODULE: 'config.settings.local'
        command: /usr/local/bin/gunicorn config.wsgi:application -w 2 -b :8000

networks:
    bilyric-net:
      external: true
