# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 03:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dualsub_favor',
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=60)),
                ('counter', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('artist', models.CharField(max_length=60, null=True)),
                ('url_video', models.CharField(max_length=255, null=True)),
                ('slug', models.CharField(max_length=200)),
                ('zmp3_id', models.CharField(max_length=45, null=True)),
                ('zmp3_xml', models.CharField(max_length=45, null=True)),
                ('bybot', models.IntegerField(default=1)),
                ('view', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('visible', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'dualsub_song',
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=60)),
                ('song_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.Song')),
                ('sub1', models.TextField(null=True)),
                ('sub2', models.TextField(null=True)),
            ],
            options={
                'db_table': 'dualsub_subtitle',
            },
        ),
        migrations.AddField(
            model_name='favor',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Song'),
        ),
        migrations.AddField(
            model_name='favor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
